services:
  atelie-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: atelie-api:latest
    container_name: atelie-api
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3001}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/atelie?schema=public}
      JWT_SECRET: ${JWT_SECRET:-changeme}
    ports:
      - '${PORT:-3001}:3001'
    networks:
      - atelieapp_network
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: atelie-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-atelie}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atelieapp_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  atelieapp_network:
    driver: bridge
